Teste/ControleAlunos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

Teste/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_aluno/', views.create_aluno, name='create_aluno'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('detail/<int:id>', views.detail, name='detail'),
]

Teste/core/models.py
from django.db import models

class Cidade(models.Model):
    nome_cidade = models.CharField(max_length = 200)
    sigla_estado = models.CharField(max_length = 2)
    def __str__(self):
        return f'{self.nome_cidade}, {self.sigla_estado}'

class Curso(models.Model):
    nome_curso = models.CharField(max_length = 200)
    def __str__(self):
        return f'{self.nome_curso}'
class Aluno(models.Model):
    nome_aluno = models.CharField(max_length = 200)
    endereco = models.CharField(max_length = 200)
    email = models.CharField(max_length = 200)
    data_nascimento = models.DateField()
    curso = models.ForeignKey(Curso, on_delete = models.CASCADE)
    cidade = models.ForeignKey(Cidade, on_delete = models.CASCADE)
    def __str__(self):
        return f'{self.nome_aluno}'

Teste/core/forms.py
from django import forms
from .models import Aluno

class AlunoForm(forms.ModelForm):
    class Meta:
        model = Aluno
        fields = '__all__'

Teste/core/views.py
from django.shortcuts import render, redirect
from .models import Aluno, Curso, Cidade
from .forms import AlunoForm

def index(request):
    alunos = Aluno.objects.all()
    cidades = Cidade.objects.all()
    cursos = Curso.objects.all()
    
    context = {
        'alunos': alunos,
        'cidades': cidades,
        'cursos': cursos,
    }

    return render(request, 'core/index.html', context)

def create_aluno(request):
    if request.method == 'POST':
        form = AlunoForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('core:index')  
    
    else:
        form = AlunoForm()
        cursos = Curso.objects.all()
        cidades = Cidade.objects.all()

        context = {
            'form': form,
            'cursos': cursos,
            'cidades': cidades
        }

    return render(request, 'core/create_aluno.html', context)

def update(request, id):

    aluno = Aluno.objects.get(id=id)

    if request.method == 'POST':
        form = AlunoForm(request.POST, instance=aluno)
        if form.is_valid():
            form.save()

            return redirect('core:index')

    else:
        cursos = Curso.objects.all()
        cidades = Cidade.objects.all()

        context = {
            'aluno': aluno,
            'cursos': cursos,
            'cidades': cidades
        }

        return render(request, 'core/update.html', context)

def delete(request, id):
    aluno = Aluno.objects.get(id = id)
    aluno.delete()

    return redirect('core:index')

def detail(request, id):
    aluno = Aluno.objects.get(id = id)

    return render(request, 'core/detail.html', {'aluno':aluno})

Teste/core/templates/core/create_aluno.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Controle de Alunos - IFRN</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body class="bg-light">

    <div class="container mt-5">

        <h1 class="display-4 mb-4">Controle de Alunos - IFRN</h1>
        <h2 class="h4 mb-4">Cadastrar novo aluno</h2>

        <form action="{% url "core:create_aluno" %}" method="POST" class="mb-4">
            {% csrf_token %}
            <div class="mb-3">
                <label for="nome_aluno" class="form-label">Nome</label>
                <input type="text" name="nome_aluno" class="form-control" id="nome_aluno" placeholder="Nome" required>
            </div>

            <div class="mb-3">
                <label for="data_nascimento" class="form-label">Data de Nascimento</label>
                <input type="date" name="data_nascimento" class="form-control" id="data_nascimento" required>
            </div>

            <div class="mb-3">
                <label for="endereco" class="form-label">Endereço</label>
                <input type="text" name="endereco" class="form-control" id="endereco" placeholder="Endereço" required>
            </div>

            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" name="email" class="form-control" id="email" placeholder="Email" required>
            </div>

            <div class="mb-3">
                <label for="curso" class="form-label">Curso</label>
                <select name="curso" id="curso" class="form-select" required>
                    {% for curso in cursos %}
                        <option value="{{curso.id}}">{{curso.nome_curso}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="cidade" class="form-label">Cidade</label>
                <select name="cidade" id="cidade" class="form-select" required>
                    {% for cidade in cidades %}
                        <option value="{{cidade.id}}">{{cidade.nome_cidade}}</option>
                    {% endfor %}
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Salvar</button>
        </form>

    </div>

</body>
</html>

Teste/core/templates/core/detail.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes do Aluno - IFRN</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body class="bg-light">

    <div class="container mt-5">

        <h1 class="display-4 mb-4">Controle de Alunos - IFRN</h1>
        <h2 class="h4 mb-4">Detalhes do Aluno</h2>

        <ul class="list-group">
            <li class="list-group-item">Nome: {{aluno.nome_aluno}}</li>
            <li class="list-group-item">Data de Nascimento: {{aluno.data_nascimento}}</li>
            <li class="list-group-item">Email: {{aluno.email}}</li>
            <li class="list-group-item">Cidade: {{aluno.cidade}}</li>
            <li class="list-group-item">Endereço: {{aluno.endereco}}</li>
            <li class="list-group-item">Curso: {{aluno.curso}}</li>
        </ul>

    </div>

</body>
</html>

Teste/core/templates/core/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Controle de Alunos - IFRN</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body class="bg-light"> 

    <div class="container mt-5">

        <h1 class="display-4 mb-4">Controle de Alunos - IFRN</h1>

        <a href="{% url "core:create_aluno" %}">
            <button type="submit" class="btn btn-primary mb-3">+ Novo Aluno</button>
        </a>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Data de nascimento</th>
                    <th scope="col">Cidade</th>
                    <th scope="col">Curso</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for aluno in alunos %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url "core:detail" aluno.id %}" class="text-decoration-none">{{aluno.nome_aluno}}</a></td>
                        <td>{{aluno.data_nascimento}}</td>
                        <td>{{aluno.cidade}}</td>
                        <td>{{aluno.curso}}</td>
                        <td>
                            <div class="d-flex"> 
                                <a href="{% url "core:update" aluno.id %}">
                                    <button type="submit" class="btn btn-warning me-2">Editar</button>
                                </a>

                                <a href="{% url "core:delete" aluno.id %}">
                                    <button type="submit" class="btn btn-danger">Excluir</button>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>

</body>
</html>

Teste/core/templates/core/update.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Controle de Alunos - IFRN</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body class="bg-light">

    <div class="container mt-5">

        <h1 class="display-4 mb-4">Controle de Alunos - IFRN</h1>

        <h2 class="h4 mb-4">Editar Aluno</h2>

        <form action="{% url "core:update" aluno.id%}" method="POST" class="mb-4">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="nome_aluno" class="form-label">Nome</label>
                <input type="text" name="nome_aluno" class="form-control" value="{{aluno.nome_aluno}}" required>
            </div>

            <div class="mb-3">
                <label for="data_nascimento" class="form-label">Data de Nascimento</label>
                <input type="date" name="data_nascimento" class="form-control" value="{{aluno.data_nascimento|date:"Y-m-d"}}" required>
            </div>

            <div class="mb-3">
                <label for="endereco" class="form-label">Endereço</label>
                <input type="text" name="endereco" class="form-control" value="{{aluno.endereco}}" required>
            </div>

            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" name="email" class="form-control" value="{{aluno.email}}" required>
            </div>

            <div class="mb-3">
                <label for="curso" class="form-label">Curso</label>
                <select name="curso" id="curso" class="form-select" required>
                    {% for curso in cursos %}
                        <option value="{{curso.id}}" {% if curso.id == aluno.curso.id %} selected {% endif %}>{{curso.nome_curso}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="cidade" class="form-label">Cidade</label>
                <select name="cidade" id="cidade" class="form-select" required>
                    {% for cidade in cidades %}
                        <option value="{{cidade.id}}" {% if cidade.id == aluno.cidade.id %} selected {% endif %}>{{cidade.nome_cidade}}</option>
                    {% endfor %}
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Salvar</button>
        </form>

    </div>

</body>
</html>